content_dir: "../content_dir"
database:
  production:
    adapter: "sqlite3"
    database: "db/production.sqlite3"
  development:
    adapter: "sqlite3"
    database: "db/development.sqlite3"
  test:
    adapter: "sqlite3"
    database: "db/test.sqlite3"

handlers:
	else:
		view: plain
		edit: plain
