source :rubygems
gem 'sinatra',         '~>1.3'
gem 'sinatra-contrib', '~>1.3'
gem 'activerecord',    '~>3.2'
gem 'warden',          '~>1.1'
gem 'sqlite3'

group :development, :test do
  gem 'shotgun'
  gem 'pry'
end

group :test do
  gem 'shoulda'
end

Dir[File.join(File.dirname(__FILE__), "plugins", "**", "Gemfile")].each do |plugin_gemfile|
  eval(IO.read(plugin_gemfile), binding)
end
